=== GSimas/EEL7303/Softwares/OrCAD/share/pcb/text/tech/cdnadrc.dtd
<!--====                                              ====-->
<!--====  Cadence PSB Extensible Markup Language DTD  ====-->
<!--====           Prototype Version 1.0              ====-->
<!--====               (cdnadrc.dtd)                  ====-->
<!--====                                              ====-->
<!--====                                              ====-->
<!--====                                              ====-->
<!--====            ADRC Properties File              ====-->

<!ELEMENT adrcProperties (adrcWireRule?, adrcDieRule?, adrcOpticalRule?, adrcDieFlagRule?, adrcMiscRule?, adrcDieStackRule?, adrcPackageSubstrateRule?)>
<!ELEMENT adrcDieRule (adrcRule)+>
<!ELEMENT adrcWireRule (adrcRule)+>
<!ELEMENT adrcMiscRule (adrcRule)+>
<!ELEMENT adrcOpticalRule (adrcRule)+>
<!ELEMENT adrcDieFlagRule (adrcRule)+>
<!ELEMENT adrcDieStackRule (adrcRule)+>
<!ELEMENT adrcPackageSubstrateRule (adrcRule)+>
<!ELEMENT adrcRule (adrcName, adrcScope?, adrcSubrule+)>
<!ELEMENT adrcSubrule (adrcConstraint+, adrcProperty*)>
<!ELEMENT adrcConstraint (adrcName, adrcValue)>
<!ELEMENT adrcProperty (adrcName, adrcValue)>
<!ELEMENT adrcName (#PCDATA)>
<!ELEMENT adrcValue (#PCDATA)>
<!ELEMENT adrcScope (#PCDATA)>

=== GSimas/EEL7303/Softwares/OrCAD/share/pcb/text/tech/adrcPropertiesMaster.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE adrcProperties SYSTEM "cdnadrc.dtd">
<!--====                                              ====-->
<!--====  Cadence PSB Extensible Markup Language      ====-->
<!--====           Prototype Version 1.1              ====-->
<!--====        (adrcPropertiesMaster.xml)            ====-->
<!--====                                              ====-->
<!--====         ADRC Properties Master file          ====-->
<!--
This file documents all the rules, their properties and constraints.
Rules can be of type adrcWireRule, adrcDieRule, adrcOpticalRule,
adrcDieFlagRule or adrcMiscRule.
The structure of a rule is name, (optional scope) and one or more subrules.
A subrule has one or more constraints and optional properties.
A constraint or property has a name and value.
Default unit of measurement for length is in microns.
For exact definition, please see the DTD file.
-->
<adrcProperties>

    <adrcWireRule>
    
        <!-- WireToComponentSpacing rule: See Section 3.19 of PRS -->
        <adrcRule>
            <adrcName>WireToComponentSpacing</adrcName>
            <adrcSubrule>
                <!-- Min. spacing between a wire and component outline -->
                <adrcConstraint>
                    <adrcName>spacing</adrcName>
                    <adrcValue>50</adrcValue>
                </adrcConstraint>
                <!-- wire profile -->
                <adrcProperty>
                    <adrcName>wireProfile</adrcName>
                    <adrcValue>PROFILE_A</adrcValue>
                </adrcProperty>
            </adrcSubrule>
        </adrcRule>
        
        <!-- WireAngleToBondFingerPad rule: See Section 3.12 of PRS -->
        <adrcRule>
            <adrcName>WireAngleToBondFingerPad</adrcName>
            <adrcSubrule>
                <!-- Max. angle between wire and bond finger axis in degrees -->
                <adrcConstraint>
                    <adrcName>maxAngle</adrcName>
                    <adrcValue>75</adrcValue>
                </adrcConstraint>
                <!-- wire profile -->
                <adrcProperty>
                    <adrcName>wireProfile</adrcName>
                    <adrcValue>PROFILE_A</adrcValue>
                </adrcProperty>
            </adrcSubrule>
        </adrcRule>
        
        <!-- WireMaximumAngleToDieEdge rule: See Section 3.11 of PRS -->
        <adrcRule>
            <adrcName>WireMaximumAngleToDieEdge</adrcName>
            <adrcSubrule>
                <!-- Max. angle between wire and orthogonal to die edge in degrees -->
                <adrcConstraint>
                    <adrcName>maxAngle</adrcName>
                    <adrcValue>75</adrcValue>
                </adrcConstraint>
                <!-- wire profile -->
                <adrcProperty>
                    <adrcName>wireProfile</adrcName>
                    <adrcValue>PROFILE_A</adrcValue>
                </adrcProperty>
            </adrcSubrule>
        </adrcRule>
        
        <!-- WireLengthDieToBondFinger rule: See Section 3.7 of PRS -->
        <adrcRule>
            <adrcName>WireLengthDieToBondFinger</adrcName>
            <adrcSubrule>
                <!-- min wire length in um -->
                <adrcConstraint>
                    <adrcName>minWireLength</adrcName>
                    <adrcValue>200</adrcValue>
                </adrcConstraint>
                <!-- max wire length in um -->
                <adrcConstraint>
                    <adrcName>maxWireLength</adrcName>
                    <adrcValue>500</adrcValue>
                </adrcConstraint>
                <!-- wire diameter in um -->
                <adrcProperty>
                    <adrcName>wireDiameter</adrcName>
                    <adrcValue>25</adrcValue>
                </adrcProperty>
                <!-- wire material -->
                <adrcProperty>
                    <adrcName>wireMaterial</adrcName>
                    <adrcValue>GOLD</adrcValue>
                </adrcProperty>
                <!-- wire profile -->
                <adrcProperty>
                    <adrcName>wireProfile</adrcName>
                    <adrcValue>PROFILE_A</adrcValue>
                </adrcProperty>
            </adrcSubrule>
        </adrcRule>

        <!-- WireLengthDieToDie rule: See Section 3.8 of PRS -->
        <!-- Exact same structure as WireLength rule -->
        <adrcRule>
            <adrcName>WireLengthDieToDie</adrcName>
            <adrcSubrule>
                <!-- min wire length in um -->
                <adrcConstraint>
                    <adrcName>minWireLength</adrcName>
                    <adrcValue>200</adrcValue>
                </adrcConstraint>
                <!-- max wire length in um -->
                <adrcConstraint>
                    <adrcName>maxWireLength</adrcName>
                    <adrcValue>500</adrcValue>
                </adrcConstraint>
                <!-- wire diameter in um -->
                <adrcProperty>
                    <adrcName>wireDiameter</adrcName>
                    <adrcValue>25</adrcValue>
                </adrcProperty>
                <!-- wire material -->
                <adrcProperty>
                    <adrcName>wireMaterial</adrcName>
                    <adrcValue>GOLD</adrcValue>
                </adrcProperty>
                <!-- wire profile -->
                <adrcProperty>
                    <adrcName>wireProfile</adrcName>
                    <adrcValue>PROFILE_A</adrcValue>
                </adrcProperty>
            </adrcSubrule>
        </adrcRule>

        <!-- WireLengthOverParentDie rule: See Section 3.9 of PRS -->
        <adrcRule>
            <adrcName>WireLengthOverParentDie</adrcName>
            <adrcSubrule>
                <!-- max wire length in um -->
                <adrcConstraint>
                    <adrcName>maxWireLength</adrcName>
                    <adrcValue>50</adrcValue>
                </adrcConstraint>
                <!-- wire diameter in um -->
                <adrcProperty>
                    <adrcName>wireDiameter</adrcName>
                    <adrcValue>25</adrcValue>
                </adrcProperty>
                <!-- wire material -->
                <adrcProperty>
                    <adrcName>wireMaterial</adrcName>
                    <adrcValue>GOLD</adrcValue>
                </adrcProperty>
                <!-- wire profile -->
                <adrcProperty>
                    <adrcName>wireProfile</adrcName>
                    <adrcValue>PROFILE_A</adrcValue>
                </adrcProperty>
                <!-- die height from the substrate -->
                <adrcProperty>
                    <adrcName>dieHeight</adrcName>
                    <adrcValue>20</adrcValue>
                </adrcProperty>
            </adrcSubrule>
            <adrcSubrule>
                <!-- max wire length in percentage -->
                <adrcConstraint>
                    <adrcName>maxPercent</adrcName>
                    <adrcValue>10</adrcValue>
                </adrcConstraint>
            </adrcSubrule>
        </adrcRule>

        <!-- WireLengthOverLowerDieStackMember rule: See Section 3.10 of PRS -->
        <!-- Exactly similar structure to WireLengthOverDie -->
        <adrcRule>
            <adrcName>WireLengthOverLowerDieStackMember</adrcName>
            <adrcSubrule>
                <!-- max wire length in um -->
                <adrcConstraint>
                    <adrcName>maxWireLength</adrcName>
                    <adrcValue>50</adrcValue>
                </adrcConstraint>
                <!-- wire diameter in um -->
                <adrcProperty>
                    <adrcName>wireDiameter</adrcName>
                    <adrcValue>25</adrcValue>
                </adrcProperty>
                <!-- wire material -->
                <adrcProperty>
                    <adrcName>wireMaterial</adrcName>
                    <adrcValue>GOLD</adrcValue>
                </adrcProperty>
                <!-- die height from the substrate -->
                <adrcProperty>
                    <adrcName>dieHeight</adrcName>
                    <adrcValue>20</adrcValue>
                </adrcProperty>
                <!-- wire profile -->
                <adrcProperty>
                    <adrcName>wireProfile</adrcName>
                    <adrcValue>PROFILE_A</adrcValue>
                </adrcProperty>
            </adrcSubrule>
            <adrcSubrule>
                <!-- max wire length in percentage -->
                <adrcConstraint>
                    <adrcName>maxPercent</adrcName>
                    <adrcValue>10</adrcValue>
                </adrcConstraint>
            </adrcSubrule>
        </adrcRule>

        <!-- WireToBondFingerSpacing rule: See Section 3.14 of PRS -->
        <adrcRule>
            <adrcName>WireToBondFingerSpacing</adrcName>
            <adrcSubrule>
                <!-- Min. spacing between a wire and bond finger in um -->
                <adrcConstraint>
                    <adrcName>spacing</adrcName>
                    <adrcValue>50</adrcValue>
                </adrcConstraint>
                <!-- wire profile -->
                <adrcProperty>
                    <adrcName>wireProfile</adrcName>
                    <adrcValue>PROFILE_A</adrcValue>
                </adrcProperty>
                <!-- other wire profile -->
                <adrcProperty>
                    <adrcName>otherWireProfile</adrcName>
                    <adrcValue>PROFILE_B</adrcValue>
                </adrcProperty>
            </adrcSubrule>
        </adrcRule>

        <!-- WireToDiePadSpacing rule -->
        <adrcRule>
            <adrcName>WireToDiePadSpacing</adrcName>
            <adrcSubrule>
                <!-- Min. spacing between a wire and die pad in um -->
                <adrcConstraint>
                    <adrcName>spacing</adrcName>
                    <adrcValue>50</adrcValue>
